version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-oficina
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: oficina_db
      MYSQL_USER: oficina_user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - oficina-net

  oficina-api:
    build: .
    container_name: oficina-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/oficina_db?useSSL=false&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: oficina_user
      SPRING_DATASOURCE_PASSWORD: senha123
    networks:
      - oficina-net

volumes:
  mysql-data:

networks:
  oficina-net:
