apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge
  labels:
    app: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
        - name: app
          image: tech-challenge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: tech-challenge-config
            - secretRef:
                name: tech-challenge-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
